apiVersion: apps/v1
kind: ReplicaSet
metadata: 
    name: ssd-monitor-rs
    labels:
        app: ssd-monitor
        env: test
        type: monitoring
spec:
    template:
        metadata:
            name: ssd-pod
            labels:
                app: ssd-monitor
                env: test
                type: monitoring
        spec:
            nodeSelector:
                disk: ssd
            containers:
              - name: ssd-container
                image: luksa/ssd-monitor

    replicas: 3
    selector:
        matchLabels:
            type: monitoring
