apiVersion: v1
kind: ReplicationController
metadata: 
    name: nginx-rc
    labels:
        app: nginx
        env: homo
        type: webserver
spec:
    template:
        metadata:
            name: nginx-pod
            labels:
                app: nginx
                env: homo
                type: webserver
        spec:
            containers:
              - name: nginx-container
                image: nginx
                ports:
                    - containerPort: 7575
    replicas: 4
