apiVersion: v1
kind: Pod
metadata:
        name: nginx-pod
        labels:
                app: nginx
                env: test
spec:
        containers:
                - name: nginx-container
                  image: nginx
        nodeSelector:
                  kubernetes.io/hostname: kubeworkernode-1  
