apiVersion: v1
kind: Pod
metadata:
    name: nginx-pod
    labels:
        app: nginx
        env: test
    namespace: custom-ns
spec:
    containers:
      - name: nginx-container
        image: nginx
