apiVersion: v1
kind: ReplicationController
metadata: 
    name: nginx-rc
    labels:
        app: nginx-app
        env: homo
        type: webserver
spec:
    template:
        metadata:
            name: nginx-pod
            labels:
                app: nginx-app
                env: homo
                type: webserver
        spec:
            containers:
              - name: nginx-container
                image: nginx
    replicas: 4
