apiVersion: apps/v1
kind: Deployment
metadata: 
    name: redis-deployment
    labels:
        app: redis
        env: prod
        type: backend
spec:
    template:
        metadata:
            name: redis-pod
            labels:
                app: redis
                env: prod
                type: backend
        spec:
            containers:
              - name: redis-container
                image: redis:4.0
    replicas: 3
    selector:
        matchLabels:
            type: backend
