apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis-slave
    labels:
        app: redis
        tier: backend
spec:
    template:
        metadata:
            name: redis-pod
            labels:
                app: redis
                role: slave
                tier: backend
        spec:
            containers:
              - name: nginx-container-slave
                image: redis
                ports:
                    - containerPort: 6379
    selector:
        matchLabels:
            app: redis
            role: slave
            tier: backend

    replicas: 3
